/*
=====================================================
Forecasting

Purpose:
Stores forecasted medicine demand
generated by the forecasting module.

Business Rules:
1. Forecasts belong to a medicine.
2. Forecasts belong to a facility.
3. Forecasts are generated monthly.
4. Multiple forecasts for the same
   month are not allowed.
=====================================================
*/

create table forecasting (

    id uuid primary key default gen_random_uuid(),

    medicine_id uuid not null
        references medicines(id)
        on delete restrict,

    facility_id uuid not null
        references facilities(id)
        on delete restrict,

    forecast_month date not null,

    predicted_quantity integer not null
        check (predicted_quantity >= 0),

    generated_at timestamptz not null
        default now(),

    constraint forecasting_unique_prediction
        unique (
            medicine_id,
            facility_id,
            forecast_month
        )
);